name = "Pyehtim"
uuid = "3d61700d-6e5b-419a-8e22-9c066cf00468"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "0.2.2"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CondaPkg = "0.2"
PythonCall = "0.9"
Reexport = "1"
julia = "1.7"

[extras]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PythonCall"]
